apiVersion: v1
kind: Service
metadata:
    name: "tailspinspacegame13237-0496"
    labels:
        app: "tailspinspacegame13237-0496"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tailspinspacegame13237-0496"